import { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { DATA_LABEL_TRANSLATIONS } from '../i18n/dataLabels';

/*
 * T4.2 (i) çok dilli arayüz — 2026-09-09.
 * - Danca ('da') 7. dil olarak eklendi (tam sözlük).
 * - 4 Dijital İkiz sayfasının (Value Chain / Manufacturing / Logistics / Product)
 *   kullanıcıya görünen sabit metinleri 'dt.*' ve sayfa önekli anahtarlara taşındı.
 *
 * ⚠️ ÇEVİRİ NOTU (taslak — native gözden geçirme gerekebilir):
 *   Aşağıdaki 'dt.*', 'vcdt.*', 'mfg.*', 'logi.*', 'prod.*' ve 'common.source'
 *   anahtarlarının de/es/fr/zh/tr/da karşılıkları ile TÜM 'da' sözlüğü model
 *   tarafından üretilmiş taslaktır; yayına çıkmadan önce native çevirmen onayı önerilir.
 *   Menü/genel metinlerin (nav/header/status/dashboard/alerts/common/onboarding/adminTour)
 *   mevcut 6 dildeki karşılıkları bu görevde DEĞİŞTİRİLMEDİ.
 *
 * Veri/KPI semantiği korunur: sayısal değerler, recharts eksen kategori verileri,
 * kaynak/provenance tanımlayıcıları (ör. unit_states, GA_NBH, TBL_Qual_Blocage
 * değerleri) ve ölçülmüş rakam taşıyan başlıklar KAYNAK DİLİNDE bırakılmıştır.
 */

export type Language = 'en' | 'de' | 'es' | 'fr' | 'zh' | 'tr' | 'da';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.dashboard': 'Dashboard',
    'nav.digitalTwin': 'Operations',
    'nav.valueChain': 'Value Chain DT',
    'nav.valueChainSim': 'Value Chain Simulation',
    'nav.manufacturing': 'Manufacturing DT',
    'nav.manufacturingSim': 'Manufacturing Simulation',
    'nav.logistics': 'Logistics DT',
    'nav.product': 'Product DT',
    'nav.sustainability': 'Sustainability Assessment',
    'nav.decisionSupport': 'Decision Support',
    'nav.moDss': 'Multi-Objective Optimization',
    'nav.knowledgeGraph': 'Decision Knowledge Graph',
    'nav.alertCenter': 'Alert Center',
    'nav.glossary': 'Glossary',
    'nav.helpTraining': 'Help & Training',
    'header.search': 'Search...',
    'header.lastHours': 'Last 24 Hours',
    'header.last7Days': 'Last 7 Days',
    'header.last30Days': 'Last 30 Days',
    'header.last90Days': 'Last 90 Days',
    'header.refresh': 'Refresh data',
    'header.notifications': 'Notifications',
    'header.language': 'Language',
    'status.online': 'System Online',
    'status.warning': 'System Warning',
    'status.critical': 'System Critical',
    'dashboard.title': 'Operations Dashboard',
    'dashboard.subtitle': 'Real-time overview of value chain performance',
    'dashboard.kpi.oee': 'Overall Equipment Effectiveness',
    'dashboard.kpi.throughput': 'Daily Throughput',
    'dashboard.kpi.defectRate': 'Defect Rate',
    'dashboard.kpi.energyEfficiency': 'Energy Efficiency',
    'dashboard.kpi.sustainability': 'Sustainability Score',
    'dashboard.kpi.supplyChainRisk': 'Supply Chain Risk Index',
    'dashboard.alerts': 'Recent Alerts',
    'dashboard.viewAll': 'View All',
    'alerts.title': 'Alert Center',
    'alerts.subtitle': 'Monitor and manage system alerts',
    'alerts.filter.all': 'All',
    'alerts.filter.critical': 'Critical',
    'alerts.filter.warning': 'Warning',
    'alerts.filter.info': 'Info',
    'alerts.acknowledge': 'Acknowledge',
    'alerts.acknowledged': 'Acknowledged',
    'alerts.details': 'Details',
    'alerts.sampleTitle': 'Sample alerts.',
    'alerts.sampleBody': 'These entries are measured from the raw {company} data — the source table, column and measured figure are printed under each alert. They illustrate the alert workflow; there is no live connection.',
    'alerts.sampleBadge': 'Sample',
    'common.apply': 'Apply',
    'common.dismiss': 'Dismiss',
    'common.seeDetails': 'See Details',
    'common.export': 'Export',
    'common.loading': 'Loading...',
    'common.error': 'An error occurred. Please try again.',
    'common.noData': 'No data available',
    'onboarding.welcome': 'Welcome to SMAP',
    'onboarding.step1.title': 'Dashboard Overview',
    'onboarding.step1.desc': 'Monitor your key performance indicators and system health at a glance.',
    'onboarding.step2.title': 'Cognitive Digital Twins',
    'onboarding.step2.desc': 'Explore real-time digital representations and run what-if simulations.',
    'onboarding.step3.title': 'Decision Support & Sustainability',
    'onboarding.step3.desc': 'Get AI-powered optimization recommendations and sustainability assessments.',
    'onboarding.step4.title': 'Alert Center',
    'onboarding.step4.desc': 'Stay informed about critical events and system notifications.',
    'onboarding.next': 'Next',
    'onboarding.prev': 'Previous',
    'onboarding.finish': 'Get Started',
    'onboarding.skip': 'Skip Tour',
    'onboarding.dontShowAgain': "Don't show this again",
    'adminTour.welcome': 'Welcome to SMAP Admin',
    'adminTour.step1.title': 'Users & Roles',
    'adminTour.step1.desc': 'Create, edit and remove accounts, and assign the manager, engineer or operator role. You only see and manage users of your own use case.',
    'adminTour.step2.title': 'Pages & Cards',
    'adminTour.step2.desc': 'Decide which pages and which cards each role can see. A change takes effect immediately in that role’s view.',
    'adminTour.step3.title': 'Scope & storage',
    'adminTour.step3.desc': 'This is a demo configuration and is stored in this browser only. It covers your own use case; the other use case is configured from its own admin account.',
    // --- Digital Twin pages (T4.2 i18n) — shared labels ---
    'dt.actual': 'Actual',
    'dt.target': 'Target',
    'dt.planned': 'Planned',
    'dt.inbound': 'Inbound',
    'dt.outbound': 'Outbound',
    'dt.suppliers': 'Suppliers',
    'dt.production': 'Production',
    'dt.customers': 'Customers',
    'dt.count': 'Count',
    'dt.onTrack': 'On Track',
    'dt.onTime': 'On Time',
    'dt.atRisk': 'At Risk',
    'dt.delayed': 'Delayed',
    'common.source': 'Source',
    // Value Chain DT
    'vcdt.title': 'Value Chain Digital Twin',
    'vcdt.subtitle': 'End-to-end visibility across the supply network',
    'vcdt.supplyChainFlow': 'Supply Chain Flow',
    'vcdt.leadTimeTrend': 'Lead Time Trend',
    'vcdt.orderStatus': 'Order Status',
    'vcdt.networkNodes': 'Network Nodes',
    'vcdt.totalOrders': 'Total Orders',
    'vcdt.help': 'View the end-to-end value chain including suppliers, production, warehousing, and distribution. Each node shows its health status and KPIs. Use the flow chart and lead time trend to identify bottlenecks.',
    'vcdt.helpLink': 'Value Chain DT guide',
    // Manufacturing DT
    'mfg.title': 'Manufacturing Digital Twin',
    'mfg.subtitle': 'Real-time production monitoring and equipment status',
    'mfg.exportReport': 'Manufacturing Digital Twin Analysis Report',
    'mfg.productionOutput': 'Production Output',
    'mfg.oeeTitle': 'OEE — Availability × Performance × Quality',
    'mfg.oeeKpiBy': 'KPI defined by IDE (KAM) and JPB',
    'mfg.oeeDesc': 'No value is shown until every leg has a connected source. Two of the three are computable from the current data; Availability arrives with the equipment stream.',
    'mfg.machineStatus': 'Machine Status',
    'mfg.machineStatusDesc': 'Per-unit state summary. The ERP extract carries no machine identity or downtime, so this view lists the four UnitModes it will be built from once the stream is connected.',
    'mfg.materialReadiness': 'Material Readiness',
    'mfg.materialReadinessDesc': 'Material issue state across open and closed shop orders.',
    'mfg.matCompletelyIssued': 'Completely Issued',
    'mfg.matPartiallyIssued': 'Partially Issued',
    'mfg.matNotReserved': 'Not Reserved',
    'mfg.pctOfTotal': '{pct}% of {total}',
    'mfg.actualVsPlanned': 'Actual vs Planned Hours',
    'mfg.actualVsPlannedDesc': 'Recorded hours against routing standard, by operation phase.',
    'mfg.cycleTime': 'Cycle Time Analysis',
    'mfg.actualSec': 'Actual (sec)',
    'mfg.targetSec': 'Target (sec)',
    'mfg.legAvailability': 'Availability',
    'mfg.legPerformance': 'Performance',
    'mfg.legQuality': 'Quality',
    'mfg.noteAvailability': 'Arrives with the equipment stream (Kafka). Not present in the ERP extract.',
    'mfg.notePerformance': 'Computable today from the shopfloor time tracking.',
    'mfg.modeProduction': 'Production',
    'mfg.modeMaintenance': 'Maintenance',
    'mfg.modeManual': 'Manual',
    'mfg.modeChangeover': 'Changeover',
    'mfg.noteModeProduction': 'Normal production mode.',
    'mfg.noteModeMaintenance': 'Equipment under maintenance.',
    'mfg.noteModeManual': 'Run under manual control.',
    'mfg.noteModeChangeover': 'Fixtures / components being changed.',
    'mfg.sourceAvailable': 'source available',
    'mfg.awaitingStream': 'awaiting stream',
    // Logistics DT
    'logi.title': 'Logistics Digital Twin',
    'logi.subtitle': 'Transportation and distribution monitoring',
    'logi.volumeTrend': 'Volume Trend',
    'logi.routePerformance': 'Route Performance',
    'logi.activeShipments': 'Active Shipments',
    'logi.timeDays': 'Time (days)',
    'logi.targetDays': 'Target (days)',
    'logi.shipments': 'shipments',
    'logi.shipInTransit': 'In Transit',
    'logi.shipDelivered': 'Delivered',
    'logi.shipPending': 'Pending',
    'logi.shipDelayed': 'Delayed',
    'logi.thShipmentId': 'Shipment ID',
    'logi.thDestination': 'Destination',
    'logi.thEta': 'ETA',
    'logi.thStatus': 'Status',
    'logi.thProgress': 'Progress',
    'logi.help': "Monitor real-time logistics data including delivery accuracy, route performance, and active shipments. Status indicators show each shipment's current state — In Transit, Delayed, or Delivered.",
    'logi.helpLink': 'Logistics DT guide',
    // Product DT
    'prod.title': 'Product Digital Twin',
    'prod.subtitle': 'Quality monitoring and product traceability',
    'prod.qualityTrend': 'Quality Trend by Batch',
    'prod.defectDistribution': 'Defect Distribution',
    'prod.productVariants': 'Product Variants Performance',
    'prod.componentTraceability': 'Component Traceability',
    'prod.receiptInspection': 'Receipt Inspection',
    'prod.yieldPct': 'Yield %',
    'prod.defectsPct': 'Defects %',
    'prod.yieldRate': 'Yield Rate',
    'prod.volume': 'Volume',
    'prod.searchComponent': 'Search component...',
    'prod.thComponent': 'Component',
    'prod.thLot': 'Lot',
    'prod.thCertificate': 'Certificate',
    'prod.thReceived': 'Received',
    'prod.thQty': 'Qty',
    'prod.thStatus': 'Status',
    'prod.thPart': 'Part',
    'prod.thArrived': 'Arrived',
    'prod.thInspected': 'Inspected',
    'prod.thScrapped': 'Scrapped',
    'prod.thReturned': 'Returned',
    'prod.helpTrace': 'Track product components across the supply chain. Click on a product variant to inspect batch quality, defect distribution, and traceability data. Red rows indicate inspection failures — click to view details.',
    'prod.helpReceipt': 'Goods receipt control per part: how much arrived, how much was inspected, and how much was scrapped or returned. KAM does not keep lot numbers, so incoming material is tracked by quantity rather than by batch.',
    'prod.helpLink': 'Product DT guide',
  },
  de: {
    'nav.dashboard': 'Dashboard',
    'nav.digitalTwin': 'Kognitive Digitale Zwillinge',
    'nav.valueChain': 'Wertschöpfungskette DT',
    'nav.valueChainSim': 'Wertschöpfungsketten-Simulation',
    'nav.manufacturing': 'Fertigung DT',
    'nav.manufacturingSim': 'Fertigungs-Simulation',
    'nav.logistics': 'Logistik DT',
    'nav.product': 'Produkt DT',
    'nav.sustainability': 'Nachhaltigkeitsbewertung',
    'nav.decisionSupport': 'Entscheidungsunterstützung',
    'nav.moDss': 'Mehrziel-Optimierung',
    'nav.knowledgeGraph': 'Entscheidungswissensgraph',
    'nav.alertCenter': 'Warnzentrale',
    'nav.glossary': 'Glossar',
    'nav.helpTraining': 'Hilfe & Schulung',
    'header.search': 'Suchen...',
    'header.lastHours': 'Letzte 24 Stunden',
    'header.last7Days': 'Letzte 7 Tage',
    'header.last30Days': 'Letzte 30 Tage',
    'header.last90Days': 'Letzte 90 Tage',
    'header.refresh': 'Daten aktualisieren',
    'header.notifications': 'Benachrichtigungen',
    'header.language': 'Sprache',
    'status.online': 'System Online',
    'status.warning': 'Systemwarnung',
    'status.critical': 'System Kritisch',
    'dashboard.title': 'Betriebs-Dashboard',
    'dashboard.subtitle': 'Echtzeit-Übersicht der Wertschöpfungskettenleistung',
    'dashboard.kpi.oee': 'Gesamtanlageneffektivität',
    'dashboard.kpi.throughput': 'Täglicher Durchsatz',
    'dashboard.kpi.defectRate': 'Fehlerquote',
    'dashboard.kpi.energyEfficiency': 'Energieeffizienz',
    'dashboard.kpi.sustainability': 'Nachhaltigkeitsbewertung',
    'dashboard.kpi.supplyChainRisk': 'Lieferkettenrisikoindex',
    'dashboard.alerts': 'Aktuelle Warnungen',
    'dashboard.viewAll': 'Alle anzeigen',
    'alerts.title': 'Warnzentrale',
    'alerts.subtitle': 'Systemwarnungen überwachen und verwalten',
    'alerts.filter.all': 'Alle',
    'alerts.filter.critical': 'Kritisch',
    'alerts.filter.warning': 'Warnung',
    'alerts.filter.info': 'Info',
    'alerts.acknowledge': 'Bestätigen',
    'alerts.acknowledged': 'Bestätigt',
    'alerts.details': 'Details',
    'alerts.sampleTitle': 'Beispielwarnungen.',
    'alerts.sampleBody': 'Diese Einträge wurden aus den Rohdaten von {company} gemessen — Quelltabelle, Spalte und gemessener Wert stehen unter jeder Warnung. Sie veranschaulichen den Warnablauf; es besteht keine Live-Verbindung.',
    'alerts.sampleBadge': 'Beispiel',
    'common.apply': 'Anwenden',
    'common.dismiss': 'Verwerfen',
    'common.seeDetails': 'Details anzeigen',
    'common.export': 'Exportieren',
    'common.loading': 'Laden...',
    'common.error': 'Ein Fehler ist aufgetreten. Bitte versuchen Sie es erneut.',
    'common.noData': 'Keine Daten verfügbar',
    'onboarding.welcome': 'Willkommen bei SMAP',
    'onboarding.step1.title': 'Dashboard-Übersicht',
    'onboarding.step1.desc': 'Überwachen Sie Ihre wichtigsten Leistungskennzahlen und den Systemzustand auf einen Blick.',
    'onboarding.step2.title': 'Kognitive Digitale Zwillinge',
    'onboarding.step2.desc': 'Erkunden Sie Echtzeit-Darstellungen und führen Sie Was-wäre-wenn-Simulationen durch.',
    'onboarding.step3.title': 'Entscheidungsunterstützung & Nachhaltigkeit',
    'onboarding.step3.desc': 'Erhalten Sie KI-gestützte Optimierungsempfehlungen und Nachhaltigkeitsbewertungen.',
    'onboarding.step4.title': 'Warnzentrale',
    'onboarding.step4.desc': 'Bleiben Sie über kritische Ereignisse und Systembenachrichtigungen informiert.',
    'onboarding.next': 'Weiter',
    'onboarding.prev': 'Zurück',
    'onboarding.finish': 'Loslegen',
    'onboarding.skip': 'Tour überspringen',
    'onboarding.dontShowAgain': 'Nicht mehr anzeigen',
    'adminTour.welcome': 'Willkommen bei SMAP Admin',
    'adminTour.step1.title': 'Benutzer & Rollen',
    'adminTour.step1.desc': 'Konten anlegen, bearbeiten und entfernen sowie die Rolle Manager, Ingenieur oder Bediener zuweisen. Sie sehen und verwalten nur Benutzer Ihres eigenen Anwendungsfalls.',
    'adminTour.step2.title': 'Seiten & Karten',
    'adminTour.step2.desc': 'Legen Sie fest, welche Seiten und Karten jede Rolle sehen darf. Eine Änderung wirkt sofort in der Ansicht dieser Rolle.',
    'adminTour.step3.title': 'Geltungsbereich & Speicherung',
    'adminTour.step3.desc': 'Dies ist eine Demo-Konfiguration und wird nur in diesem Browser gespeichert. Sie gilt für Ihren eigenen Anwendungsfall; der andere Anwendungsfall wird über sein eigenes Administratorkonto konfiguriert.',
    // --- Digital Twin pages (T4.2 i18n) — taslak çeviri / draft ---
    'dt.actual': 'Ist',
    'dt.target': 'Ziel',
    'dt.planned': 'Geplant',
    'dt.inbound': 'Eingang',
    'dt.outbound': 'Ausgang',
    'dt.suppliers': 'Lieferanten',
    'dt.production': 'Produktion',
    'dt.customers': 'Kunden',
    'dt.count': 'Anzahl',
    'dt.onTrack': 'Im Plan',
    'dt.onTime': 'Pünktlich',
    'dt.atRisk': 'Gefährdet',
    'dt.delayed': 'Verspätet',
    'common.source': 'Quelle',
    'vcdt.title': 'Wertschöpfungsketten-Digitaler Zwilling',
    'vcdt.subtitle': 'Durchgängige Transparenz im Liefernetzwerk',
    'vcdt.supplyChainFlow': 'Lieferkettenfluss',
    'vcdt.leadTimeTrend': 'Durchlaufzeit-Trend',
    'vcdt.orderStatus': 'Auftragsstatus',
    'vcdt.networkNodes': 'Netzwerkknoten',
    'vcdt.totalOrders': 'Aufträge gesamt',
    'vcdt.help': 'Betrachten Sie die durchgängige Wertschöpfungskette mit Lieferanten, Produktion, Lagerung und Distribution. Jeder Knoten zeigt seinen Zustand und seine KPIs. Nutzen Sie das Flussdiagramm und den Durchlaufzeit-Trend, um Engpässe zu erkennen.',
    'vcdt.helpLink': 'Leitfaden Wertschöpfungsketten-DT',
    'mfg.title': 'Fertigungs-Digitaler Zwilling',
    'mfg.subtitle': 'Echtzeit-Produktionsüberwachung und Anlagenstatus',
    'mfg.exportReport': 'Analysebericht Fertigungs-Digitaler Zwilling',
    'mfg.productionOutput': 'Produktionsausstoß',
    'mfg.oeeTitle': 'OEE — Verfügbarkeit × Leistung × Qualität',
    'mfg.oeeKpiBy': 'KPI definiert von IDE (KAM) und JPB',
    'mfg.oeeDesc': 'Es wird kein Wert angezeigt, bis jeder Teilwert eine verbundene Quelle hat. Zwei der drei sind aus den aktuellen Daten berechenbar; die Verfügbarkeit kommt mit dem Anlagen-Stream.',
    'mfg.machineStatus': 'Maschinenstatus',
    'mfg.machineStatusDesc': 'Zustandsübersicht je Einheit. Der ERP-Export enthält keine Maschinenidentität oder Stillstandszeiten, daher listet diese Ansicht die vier UnitModes auf, aus denen sie nach Anbindung des Streams aufgebaut wird.',
    'mfg.materialReadiness': 'Materialbereitschaft',
    'mfg.materialReadinessDesc': 'Materialbereitstellungsstatus über offene und abgeschlossene Fertigungsaufträge.',
    'mfg.matCompletelyIssued': 'Vollständig ausgegeben',
    'mfg.matPartiallyIssued': 'Teilweise ausgegeben',
    'mfg.matNotReserved': 'Nicht reserviert',
    'mfg.pctOfTotal': '{pct}% von {total}',
    'mfg.actualVsPlanned': 'Ist- vs. Planstunden',
    'mfg.actualVsPlannedDesc': 'Erfasste Stunden gegenüber dem Routing-Standard, nach Arbeitsgangphase.',
    'mfg.cycleTime': 'Taktzeitanalyse',
    'mfg.actualSec': 'Ist (Sek.)',
    'mfg.targetSec': 'Ziel (Sek.)',
    'mfg.legAvailability': 'Verfügbarkeit',
    'mfg.legPerformance': 'Leistung',
    'mfg.legQuality': 'Qualität',
    'mfg.noteAvailability': 'Kommt mit dem Anlagen-Stream (Kafka). Im ERP-Export nicht vorhanden.',
    'mfg.notePerformance': 'Heute aus der Betriebsdatenerfassung berechenbar.',
    'mfg.modeProduction': 'Produktion',
    'mfg.modeMaintenance': 'Wartung',
    'mfg.modeManual': 'Manuell',
    'mfg.modeChangeover': 'Umrüstung',
    'mfg.noteModeProduction': 'Normaler Produktionsmodus.',
    'mfg.noteModeMaintenance': 'Anlage in Wartung.',
    'mfg.noteModeManual': 'Betrieb unter manueller Steuerung.',
    'mfg.noteModeChangeover': 'Vorrichtungen / Komponenten werden gewechselt.',
    'mfg.sourceAvailable': 'Quelle verfügbar',
    'mfg.awaitingStream': 'Stream ausstehend',
    'logi.title': 'Logistik-Digitaler Zwilling',
    'logi.subtitle': 'Transport- und Distributionsüberwachung',
    'logi.volumeTrend': 'Volumentrend',
    'logi.routePerformance': 'Routenleistung',
    'logi.activeShipments': 'Aktive Sendungen',
    'logi.timeDays': 'Zeit (Tage)',
    'logi.targetDays': 'Ziel (Tage)',
    'logi.shipments': 'Sendungen',
    'logi.shipInTransit': 'Unterwegs',
    'logi.shipDelivered': 'Zugestellt',
    'logi.shipPending': 'Ausstehend',
    'logi.shipDelayed': 'Verspätet',
    'logi.thShipmentId': 'Sendungs-ID',
    'logi.thDestination': 'Ziel',
    'logi.thEta': 'Voraussichtl. Ankunft',
    'logi.thStatus': 'Status',
    'logi.thProgress': 'Fortschritt',
    'logi.help': 'Überwachen Sie Logistikdaten in Echtzeit, einschließlich Lieferzuverlässigkeit, Routenleistung und aktiven Sendungen. Statusanzeigen zeigen den aktuellen Zustand jeder Sendung — Unterwegs, Verspätet oder Zugestellt.',
    'logi.helpLink': 'Leitfaden Logistik-DT',
    'prod.title': 'Produkt-Digitaler Zwilling',
    'prod.subtitle': 'Qualitätsüberwachung und Produktrückverfolgbarkeit',
    'prod.qualityTrend': 'Qualitätstrend nach Charge',
    'prod.defectDistribution': 'Fehlerverteilung',
    'prod.productVariants': 'Leistung der Produktvarianten',
    'prod.componentTraceability': 'Komponenten-Rückverfolgbarkeit',
    'prod.receiptInspection': 'Wareneingangsprüfung',
    'prod.yieldPct': 'Ausbeute %',
    'prod.defectsPct': 'Fehler %',
    'prod.yieldRate': 'Ausbeutequote',
    'prod.volume': 'Volumen',
    'prod.searchComponent': 'Komponente suchen...',
    'prod.thComponent': 'Komponente',
    'prod.thLot': 'Los',
    'prod.thCertificate': 'Zertifikat',
    'prod.thReceived': 'Eingegangen',
    'prod.thQty': 'Menge',
    'prod.thStatus': 'Status',
    'prod.thPart': 'Teil',
    'prod.thArrived': 'Angekommen',
    'prod.thInspected': 'Geprüft',
    'prod.thScrapped': 'Ausschuss',
    'prod.thReturned': 'Zurückgesendet',
    'prod.helpTrace': 'Verfolgen Sie Produktkomponenten über die Lieferkette hinweg. Klicken Sie auf eine Produktvariante, um Chargenqualität, Fehlerverteilung und Rückverfolgbarkeitsdaten zu prüfen. Rote Zeilen weisen auf Prüffehler hin — zum Anzeigen der Details klicken.',
    'prod.helpReceipt': 'Wareneingangskontrolle je Teil: wie viel ankam, wie viel geprüft und wie viel verschrottet oder zurückgesendet wurde. KAM führt keine Losnummern, daher wird eingehendes Material nach Menge statt nach Charge verfolgt.',
    'prod.helpLink': 'Leitfaden Produkt-DT',
  },
  es: {
    'nav.dashboard': 'Panel de Control',
    'nav.digitalTwin': 'Gemelos Digitales Cognitivos',
    'nav.valueChain': 'Cadena de Valor DT',
    'nav.valueChainSim': 'Simulación de Cadena de Valor',
    'nav.manufacturing': 'Fabricación DT',
    'nav.manufacturingSim': 'Simulación de Fabricación',
    'nav.logistics': 'Logística DT',
    'nav.product': 'Producto DT',
    'nav.sustainability': 'Evaluación de Sostenibilidad',
    'nav.decisionSupport': 'Soporte de Decisiones',
    'nav.moDss': 'Optimización Multiobjetivo',
    'nav.knowledgeGraph': 'Grafo de Conocimiento de Decisiones',
    'nav.alertCenter': 'Centro de Alertas',
    'nav.glossary': 'Glosario',
    'nav.helpTraining': 'Ayuda y Formación',
    'header.search': 'Buscar...',
    'header.lastHours': 'Últimas 24 Horas',
    'header.last7Days': 'Últimos 7 Días',
    'header.last30Days': 'Últimos 30 Días',
    'header.last90Days': 'Últimos 90 Días',
    'header.refresh': 'Actualizar datos',
    'header.notifications': 'Notificaciones',
    'header.language': 'Idioma',
    'status.online': 'Sistema en Línea',
    'status.warning': 'Advertencia del Sistema',
    'status.critical': 'Sistema Crítico',
    'dashboard.title': 'Panel de Operaciones',
    'dashboard.subtitle': 'Vista general en tiempo real del rendimiento de la cadena de valor',
    'dashboard.kpi.oee': 'Efectividad General del Equipo',
    'dashboard.kpi.throughput': 'Rendimiento Diario',
    'dashboard.kpi.defectRate': 'Tasa de Defectos',
    'dashboard.kpi.energyEfficiency': 'Eficiencia Energética',
    'dashboard.kpi.sustainability': 'Puntuación de Sostenibilidad',
    'dashboard.kpi.supplyChainRisk': 'Índice de Riesgo de Cadena de Suministro',
    'dashboard.alerts': 'Alertas Recientes',
    'dashboard.viewAll': 'Ver Todas',
    'alerts.title': 'Centro de Alertas',
    'alerts.subtitle': 'Monitorear y gestionar alertas del sistema',
    'alerts.filter.all': 'Todas',
    'alerts.filter.critical': 'Críticas',
    'alerts.filter.warning': 'Advertencias',
    'alerts.filter.info': 'Info',
    'alerts.acknowledge': 'Reconocer',
    'alerts.acknowledged': 'Reconocida',
    'alerts.details': 'Detalles',
    'alerts.sampleTitle': 'Alertas de ejemplo.',
    'alerts.sampleBody': 'Estas entradas se midieron a partir de los datos brutos de {company}: la tabla de origen, la columna y el valor medido aparecen debajo de cada alerta. Ilustran el flujo de alertas; no hay conexión en vivo.',
    'alerts.sampleBadge': 'Ejemplo',
    'common.apply': 'Aplicar',
    'common.dismiss': 'Descartar',
    'common.seeDetails': 'Ver Detalles',
    'common.export': 'Exportar',
    'common.loading': 'Cargando...',
    'common.error': 'Ocurrió un error. Por favor, inténtelo de nuevo.',
    'common.noData': 'No hay datos disponibles',
    'onboarding.welcome': 'Bienvenido a SMAP',
    'onboarding.step1.title': 'Vista General del Panel',
    'onboarding.step1.desc': 'Monitoree sus indicadores clave de rendimiento y el estado del sistema de un vistazo.',
    'onboarding.step2.title': 'Gemelos Digitales Cognitivos',
    'onboarding.step2.desc': 'Explore representaciones digitales en tiempo real y ejecute simulaciones hipotéticas.',
    'onboarding.step3.title': 'Soporte de Decisiones y Sostenibilidad',
    'onboarding.step3.desc': 'Obtenga recomendaciones de optimización con IA y evaluaciones de sostenibilidad.',
    'onboarding.step4.title': 'Centro de Alertas',
    'onboarding.step4.desc': 'Manténgase informado sobre eventos críticos y notificaciones del sistema.',
    'onboarding.next': 'Siguiente',
    'onboarding.prev': 'Anterior',
    'onboarding.finish': 'Comenzar',
    'onboarding.skip': 'Saltar Tour',
    'onboarding.dontShowAgain': 'No volver a mostrar',
    'adminTour.welcome': 'Bienvenido a SMAP Admin',
    'adminTour.step1.title': 'Usuarios y Roles',
    'adminTour.step1.desc': 'Cree, edite y elimine cuentas, y asigne el rol de gerente, ingeniero u operador. Solo ve y gestiona los usuarios de su propio caso de uso.',
    'adminTour.step2.title': 'Páginas y Tarjetas',
    'adminTour.step2.desc': 'Decida qué páginas y qué tarjetas puede ver cada rol. El cambio se aplica de inmediato en la vista de ese rol.',
    'adminTour.step3.title': 'Alcance y almacenamiento',
    'adminTour.step3.desc': 'Esta es una configuración de demostración y se guarda únicamente en este navegador. Cubre su propio caso de uso; el otro caso de uso se configura desde su propia cuenta de administrador.',
    // --- Digital Twin pages (T4.2 i18n) — taslak çeviri / draft ---
    'dt.actual': 'Real',
    'dt.target': 'Objetivo',
    'dt.planned': 'Planificado',
    'dt.inbound': 'Entrante',
    'dt.outbound': 'Saliente',
    'dt.suppliers': 'Proveedores',
    'dt.production': 'Producción',
    'dt.customers': 'Clientes',
    'dt.count': 'Cantidad',
    'dt.onTrack': 'En curso',
    'dt.onTime': 'A tiempo',
    'dt.atRisk': 'En riesgo',
    'dt.delayed': 'Retrasado',
    'common.source': 'Fuente',
    'vcdt.title': 'Gemelo Digital de la Cadena de Valor',
    'vcdt.subtitle': 'Visibilidad integral en toda la red de suministro',
    'vcdt.supplyChainFlow': 'Flujo de la Cadena de Suministro',
    'vcdt.leadTimeTrend': 'Tendencia del Tiempo de Entrega',
    'vcdt.orderStatus': 'Estado de Pedidos',
    'vcdt.networkNodes': 'Nodos de la Red',
    'vcdt.totalOrders': 'Pedidos Totales',
    'vcdt.help': 'Visualice la cadena de valor integral, incluidos proveedores, producción, almacenamiento y distribución. Cada nodo muestra su estado de salud y sus KPI. Use el diagrama de flujo y la tendencia del tiempo de entrega para identificar cuellos de botella.',
    'vcdt.helpLink': 'Guía del DT de Cadena de Valor',
    'mfg.title': 'Gemelo Digital de Fabricación',
    'mfg.subtitle': 'Monitoreo de producción en tiempo real y estado de los equipos',
    'mfg.exportReport': 'Informe de Análisis del Gemelo Digital de Fabricación',
    'mfg.productionOutput': 'Salida de Producción',
    'mfg.oeeTitle': 'OEE — Disponibilidad × Rendimiento × Calidad',
    'mfg.oeeKpiBy': 'KPI definido por IDE (KAM) y JPB',
    'mfg.oeeDesc': 'No se muestra ningún valor hasta que cada componente tenga una fuente conectada. Dos de los tres son calculables con los datos actuales; la disponibilidad llega con el flujo de equipos.',
    'mfg.machineStatus': 'Estado de las Máquinas',
    'mfg.machineStatusDesc': 'Resumen de estado por unidad. El extracto ERP no incluye identidad de máquina ni tiempos de inactividad, por lo que esta vista enumera los cuatro UnitModes con los que se construirá una vez conectado el flujo.',
    'mfg.materialReadiness': 'Disponibilidad de Material',
    'mfg.materialReadinessDesc': 'Estado de entrega de material en órdenes de trabajo abiertas y cerradas.',
    'mfg.matCompletelyIssued': 'Entregado por completo',
    'mfg.matPartiallyIssued': 'Entregado parcialmente',
    'mfg.matNotReserved': 'No reservado',
    'mfg.pctOfTotal': '{pct}% de {total}',
    'mfg.actualVsPlanned': 'Horas Reales vs Planificadas',
    'mfg.actualVsPlannedDesc': 'Horas registradas frente al estándar de ruta, por fase de operación.',
    'mfg.cycleTime': 'Análisis del Tiempo de Ciclo',
    'mfg.actualSec': 'Real (s)',
    'mfg.targetSec': 'Objetivo (s)',
    'mfg.legAvailability': 'Disponibilidad',
    'mfg.legPerformance': 'Rendimiento',
    'mfg.legQuality': 'Calidad',
    'mfg.noteAvailability': 'Llega con el flujo de equipos (Kafka). No está presente en el extracto ERP.',
    'mfg.notePerformance': 'Calculable hoy a partir del seguimiento de tiempos en planta.',
    'mfg.modeProduction': 'Producción',
    'mfg.modeMaintenance': 'Mantenimiento',
    'mfg.modeManual': 'Manual',
    'mfg.modeChangeover': 'Cambio de formato',
    'mfg.noteModeProduction': 'Modo de producción normal.',
    'mfg.noteModeMaintenance': 'Equipo en mantenimiento.',
    'mfg.noteModeManual': 'Operación bajo control manual.',
    'mfg.noteModeChangeover': 'Se están cambiando utillajes / componentes.',
    'mfg.sourceAvailable': 'fuente disponible',
    'mfg.awaitingStream': 'esperando flujo',
    'logi.title': 'Gemelo Digital de Logística',
    'logi.subtitle': 'Monitoreo de transporte y distribución',
    'logi.volumeTrend': 'Tendencia de Volumen',
    'logi.routePerformance': 'Rendimiento de Rutas',
    'logi.activeShipments': 'Envíos Activos',
    'logi.timeDays': 'Tiempo (días)',
    'logi.targetDays': 'Objetivo (días)',
    'logi.shipments': 'envíos',
    'logi.shipInTransit': 'En tránsito',
    'logi.shipDelivered': 'Entregado',
    'logi.shipPending': 'Pendiente',
    'logi.shipDelayed': 'Retrasado',
    'logi.thShipmentId': 'ID de Envío',
    'logi.thDestination': 'Destino',
    'logi.thEta': 'ETA',
    'logi.thStatus': 'Estado',
    'logi.thProgress': 'Progreso',
    'logi.help': 'Monitoree datos logísticos en tiempo real, incluida la precisión de entrega, el rendimiento de rutas y los envíos activos. Los indicadores de estado muestran el estado actual de cada envío: En tránsito, Retrasado o Entregado.',
    'logi.helpLink': 'Guía del DT de Logística',
    'prod.title': 'Gemelo Digital de Producto',
    'prod.subtitle': 'Monitoreo de calidad y trazabilidad del producto',
    'prod.qualityTrend': 'Tendencia de Calidad por Lote',
    'prod.defectDistribution': 'Distribución de Defectos',
    'prod.productVariants': 'Rendimiento de Variantes de Producto',
    'prod.componentTraceability': 'Trazabilidad de Componentes',
    'prod.receiptInspection': 'Inspección de Recepción',
    'prod.yieldPct': 'Rendimiento %',
    'prod.defectsPct': 'Defectos %',
    'prod.yieldRate': 'Tasa de Rendimiento',
    'prod.volume': 'Volumen',
    'prod.searchComponent': 'Buscar componente...',
    'prod.thComponent': 'Componente',
    'prod.thLot': 'Lote',
    'prod.thCertificate': 'Certificado',
    'prod.thReceived': 'Recibido',
    'prod.thQty': 'Cant.',
    'prod.thStatus': 'Estado',
    'prod.thPart': 'Pieza',
    'prod.thArrived': 'Llegado',
    'prod.thInspected': 'Inspeccionado',
    'prod.thScrapped': 'Desechado',
    'prod.thReturned': 'Devuelto',
    'prod.helpTrace': 'Rastree los componentes del producto a lo largo de la cadena de suministro. Haga clic en una variante de producto para inspeccionar la calidad del lote, la distribución de defectos y los datos de trazabilidad. Las filas rojas indican fallos de inspección: haga clic para ver los detalles.',
    'prod.helpReceipt': 'Control de recepción de mercancías por pieza: cuánto llegó, cuánto se inspeccionó y cuánto se desechó o devolvió. KAM no mantiene números de lote, por lo que el material entrante se rastrea por cantidad en lugar de por lote.',
    'prod.helpLink': 'Guía del DT de Producto',
  },
  fr: {
    'nav.dashboard': 'Tableau de Bord',
    'nav.digitalTwin': 'Jumeaux Numériques Cognitifs',
    'nav.valueChain': 'Chaîne de Valeur DT',
    'nav.valueChainSim': 'Simulation de Chaîne de Valeur',
    'nav.manufacturing': 'Fabrication DT',
    'nav.manufacturingSim': 'Simulation de Fabrication',
    'nav.logistics': 'Logistique DT',
    'nav.product': 'Produit DT',
    'nav.sustainability': 'Évaluation de Durabilité',
    'nav.decisionSupport': 'Aide à la Décision',
    'nav.moDss': 'Optimisation Multi-Objectifs',
    'nav.knowledgeGraph': 'Graphe de Connaissances Décisionnelles',
    'nav.alertCenter': "Centre d'Alertes",
    'nav.glossary': 'Glossaire',
    'nav.helpTraining': 'Aide & Formation',
    'header.search': 'Rechercher...',
    'header.lastHours': 'Dernières 24 Heures',
    'header.last7Days': '7 Derniers Jours',
    'header.last30Days': '30 Derniers Jours',
    'header.last90Days': '90 Derniers Jours',
    'header.refresh': 'Actualiser les données',
    'header.notifications': 'Notifications',
    'header.language': 'Langue',
    'status.online': 'Système en Ligne',
    'status.warning': 'Avertissement Système',
    'status.critical': 'Système Critique',
    'dashboard.title': 'Tableau de Bord Opérationnel',
    'dashboard.subtitle': 'Vue en temps réel de la performance de la chaîne de valeur',
    'dashboard.kpi.oee': 'Efficacité Globale des Équipements',
    'dashboard.kpi.throughput': 'Débit Quotidien',
    'dashboard.kpi.defectRate': 'Taux de Défauts',
    'dashboard.kpi.energyEfficiency': 'Efficacité Énergétique',
    'dashboard.kpi.sustainability': 'Score de Durabilité',
    'dashboard.kpi.supplyChainRisk': "Indice de Risque de la Chaîne d'Approvisionnement",
    'dashboard.alerts': 'Alertes Récentes',
    'dashboard.viewAll': 'Voir Tout',
    'alerts.title': "Centre d'Alertes",
    'alerts.subtitle': 'Surveiller et gérer les alertes système',
    'alerts.filter.all': 'Toutes',
    'alerts.filter.critical': 'Critiques',
    'alerts.filter.warning': 'Avertissements',
    'alerts.filter.info': 'Info',
    'alerts.acknowledge': 'Acquitter',
    'alerts.acknowledged': 'Acquittée',
    'alerts.details': 'Détails',
    'alerts.sampleTitle': 'Alertes d’exemple.',
    'alerts.sampleBody': 'Ces entrées sont mesurées à partir des données brutes de {company} — la table source, la colonne et la valeur mesurée figurent sous chaque alerte. Elles illustrent le flux d’alertes ; il n’y a aucune connexion en direct.',
    'alerts.sampleBadge': 'Exemple',
    'common.apply': 'Appliquer',
    'common.dismiss': 'Rejeter',
    'common.seeDetails': 'Voir Détails',
    'common.export': 'Exporter',
    'common.loading': 'Chargement...',
    'common.error': 'Une erreur est survenue. Veuillez réessayer.',
    'common.noData': 'Aucune donnée disponible',
    'onboarding.welcome': 'Bienvenue sur SMAP',
    'onboarding.step1.title': 'Aperçu du Tableau de Bord',
    'onboarding.step1.desc': "Surveillez vos indicateurs clés de performance et l'état du système en un coup d'œil.",
    'onboarding.step2.title': 'Jumeaux Numériques Cognitifs',
    'onboarding.step2.desc': 'Explorez les représentations numériques en temps réel et lancez des simulations.',
    'onboarding.step3.title': 'Aide à la Décision & Durabilité',
    'onboarding.step3.desc': "Obtenez des recommandations d'optimisation par l'IA et des évaluations de durabilité.",
    'onboarding.step4.title': "Centre d'Alertes",
    'onboarding.step4.desc': 'Restez informé des événements critiques et des notifications système.',
    'onboarding.next': 'Suivant',
    'onboarding.prev': 'Précédent',
    'onboarding.finish': 'Commencer',
    'onboarding.skip': 'Passer le Tour',
    'onboarding.dontShowAgain': 'Ne plus afficher',
    'adminTour.welcome': 'Bienvenue sur SMAP Admin',
    'adminTour.step1.title': 'Utilisateurs et Rôles',
    'adminTour.step1.desc': "Créez, modifiez et supprimez des comptes, et attribuez le rôle de responsable, d'ingénieur ou d'opérateur. Vous ne voyez et ne gérez que les utilisateurs de votre propre cas d'usage.",
    'adminTour.step2.title': 'Pages et Cartes',
    'adminTour.step2.desc': "Déterminez quelles pages et quelles cartes chaque rôle peut voir. Une modification s'applique immédiatement à la vue de ce rôle.",
    'adminTour.step3.title': 'Périmètre et stockage',
    'adminTour.step3.desc': "Il s'agit d'une configuration de démonstration, enregistrée uniquement dans ce navigateur. Elle couvre votre propre cas d'usage ; l'autre cas d'usage se configure depuis son propre compte administrateur.",
    // --- Digital Twin pages (T4.2 i18n) — taslak çeviri / draft ---
    'dt.actual': 'Réel',
    'dt.target': 'Cible',
    'dt.planned': 'Planifié',
    'dt.inbound': 'Entrant',
    'dt.outbound': 'Sortant',
    'dt.suppliers': 'Fournisseurs',
    'dt.production': 'Production',
    'dt.customers': 'Clients',
    'dt.count': 'Nombre',
    'dt.onTrack': 'Dans les temps',
    'dt.onTime': "À l'heure",
    'dt.atRisk': 'À risque',
    'dt.delayed': 'En retard',
    'common.source': 'Source',
    'vcdt.title': 'Jumeau Numérique de la Chaîne de Valeur',
    'vcdt.subtitle': "Visibilité de bout en bout sur le réseau d'approvisionnement",
    'vcdt.supplyChainFlow': "Flux de la Chaîne d'Approvisionnement",
    'vcdt.leadTimeTrend': 'Tendance des Délais',
    'vcdt.orderStatus': 'Statut des Commandes',
    'vcdt.networkNodes': 'Nœuds du Réseau',
    'vcdt.totalOrders': 'Commandes Totales',
    'vcdt.help': "Visualisez la chaîne de valeur de bout en bout, y compris les fournisseurs, la production, l'entreposage et la distribution. Chaque nœud affiche son état de santé et ses KPI. Utilisez le diagramme de flux et la tendance des délais pour repérer les goulets d'étranglement.",
    'vcdt.helpLink': 'Guide du JN Chaîne de Valeur',
    'mfg.title': 'Jumeau Numérique de Fabrication',
    'mfg.subtitle': 'Surveillance de la production en temps réel et état des équipements',
    'mfg.exportReport': "Rapport d'Analyse du Jumeau Numérique de Fabrication",
    'mfg.productionOutput': 'Volume de Production',
    'mfg.oeeTitle': 'OEE — Disponibilité × Performance × Qualité',
    'mfg.oeeKpiBy': 'KPI défini par IDE (KAM) et JPB',
    'mfg.oeeDesc': "Aucune valeur n'est affichée tant que chaque composante n'a pas de source connectée. Deux des trois sont calculables à partir des données actuelles ; la disponibilité arrive avec le flux des équipements.",
    'mfg.machineStatus': 'État des Machines',
    'mfg.machineStatusDesc': "Résumé d'état par unité. L'extraction ERP ne contient ni identité machine ni temps d'arrêt ; cette vue liste donc les quatre UnitModes à partir desquels elle sera construite une fois le flux connecté.",
    'mfg.materialReadiness': 'Disponibilité des Matières',
    'mfg.materialReadinessDesc': 'État de sortie des matières sur les ordres de fabrication ouverts et clos.',
    'mfg.matCompletelyIssued': 'Entièrement sorti',
    'mfg.matPartiallyIssued': 'Partiellement sorti',
    'mfg.matNotReserved': 'Non réservé',
    'mfg.pctOfTotal': '{pct}% sur {total}',
    'mfg.actualVsPlanned': 'Heures Réelles vs Planifiées',
    'mfg.actualVsPlannedDesc': "Heures enregistrées par rapport au standard de gamme, par phase d'opération.",
    'mfg.cycleTime': 'Analyse du Temps de Cycle',
    'mfg.actualSec': 'Réel (s)',
    'mfg.targetSec': 'Cible (s)',
    'mfg.legAvailability': 'Disponibilité',
    'mfg.legPerformance': 'Performance',
    'mfg.legQuality': 'Qualité',
    'mfg.noteAvailability': "Arrive avec le flux des équipements (Kafka). Absent de l'extraction ERP.",
    'mfg.notePerformance': "Calculable aujourd'hui à partir du suivi des temps en atelier.",
    'mfg.modeProduction': 'Production',
    'mfg.modeMaintenance': 'Maintenance',
    'mfg.modeManual': 'Manuel',
    'mfg.modeChangeover': 'Changement de série',
    'mfg.noteModeProduction': 'Mode de production normal.',
    'mfg.noteModeMaintenance': 'Équipement en maintenance.',
    'mfg.noteModeManual': 'Fonctionnement en commande manuelle.',
    'mfg.noteModeChangeover': 'Changement de montages / composants en cours.',
    'mfg.sourceAvailable': 'source disponible',
    'mfg.awaitingStream': 'en attente du flux',
    'logi.title': 'Jumeau Numérique de Logistique',
    'logi.subtitle': 'Surveillance du transport et de la distribution',
    'logi.volumeTrend': 'Tendance des Volumes',
    'logi.routePerformance': 'Performance des Itinéraires',
    'logi.activeShipments': 'Expéditions Actives',
    'logi.timeDays': 'Temps (jours)',
    'logi.targetDays': 'Cible (jours)',
    'logi.shipments': 'expéditions',
    'logi.shipInTransit': 'En transit',
    'logi.shipDelivered': 'Livré',
    'logi.shipPending': 'En attente',
    'logi.shipDelayed': 'En retard',
    'logi.thShipmentId': "ID d'Expédition",
    'logi.thDestination': 'Destination',
    'logi.thEta': 'ETA',
    'logi.thStatus': 'Statut',
    'logi.thProgress': 'Progression',
    'logi.help': "Surveillez les données logistiques en temps réel, y compris la précision des livraisons, la performance des itinéraires et les expéditions actives. Les indicateurs de statut montrent l'état actuel de chaque expédition — En transit, En retard ou Livré.",
    'logi.helpLink': 'Guide du JN Logistique',
    'prod.title': 'Jumeau Numérique de Produit',
    'prod.subtitle': 'Surveillance de la qualité et traçabilité du produit',
    'prod.qualityTrend': 'Tendance de Qualité par Lot',
    'prod.defectDistribution': 'Distribution des Défauts',
    'prod.productVariants': 'Performance des Variantes de Produit',
    'prod.componentTraceability': 'Traçabilité des Composants',
    'prod.receiptInspection': 'Contrôle à Réception',
    'prod.yieldPct': 'Rendement %',
    'prod.defectsPct': 'Défauts %',
    'prod.yieldRate': 'Taux de Rendement',
    'prod.volume': 'Volume',
    'prod.searchComponent': 'Rechercher un composant...',
    'prod.thComponent': 'Composant',
    'prod.thLot': 'Lot',
    'prod.thCertificate': 'Certificat',
    'prod.thReceived': 'Reçu',
    'prod.thQty': 'Qté',
    'prod.thStatus': 'Statut',
    'prod.thPart': 'Pièce',
    'prod.thArrived': 'Arrivé',
    'prod.thInspected': 'Inspecté',
    'prod.thScrapped': 'Rebuté',
    'prod.thReturned': 'Retourné',
    'prod.helpTrace': "Suivez les composants du produit tout au long de la chaîne d'approvisionnement. Cliquez sur une variante de produit pour inspecter la qualité du lot, la distribution des défauts et les données de traçabilité. Les lignes rouges indiquent des échecs de contrôle — cliquez pour voir les détails.",
    'prod.helpReceipt': "Contrôle de réception des marchandises par pièce : quantité arrivée, quantité inspectée et quantité rebutée ou retournée. KAM ne conserve pas de numéros de lot ; le matériel entrant est donc suivi par quantité plutôt que par lot.",
    'prod.helpLink': 'Guide du JN Produit',
  },
  zh: {
    'nav.dashboard': '仪表板',
    'nav.digitalTwin': '认知数字孪生',
    'nav.valueChain': '价值链 DT',
    'nav.valueChainSim': '价值链仿真',
    'nav.manufacturing': '制造 DT',
    'nav.manufacturingSim': '制造仿真',
    'nav.logistics': '物流 DT',
    'nav.product': '产品 DT',
    'nav.sustainability': '可持续性评估',
    'nav.decisionSupport': '决策支持',
    'nav.moDss': '多目标优化',
    'nav.knowledgeGraph': '决策知识图谱',
    'nav.alertCenter': '警报中心',
    'nav.glossary': '术语表',
    'nav.helpTraining': '帮助与培训',
    'header.search': '搜索...',
    'header.lastHours': '过去24小时',
    'header.last7Days': '过去7天',
    'header.last30Days': '过去30天',
    'header.last90Days': '过去90天',
    'header.refresh': '刷新数据',
    'header.notifications': '通知',
    'header.language': '语言',
    'status.online': '系统在线',
    'status.warning': '系统警告',
    'status.critical': '系统危急',
    'dashboard.title': '运营仪表板',
    'dashboard.subtitle': '价值链绩效实时概览',
    'dashboard.kpi.oee': '整体设备效率',
    'dashboard.kpi.throughput': '日吞吐量',
    'dashboard.kpi.defectRate': '缺陷率',
    'dashboard.kpi.energyEfficiency': '能源效率',
    'dashboard.kpi.sustainability': '可持续性评分',
    'dashboard.kpi.supplyChainRisk': '供应链风险指数',
    'dashboard.alerts': '最近警报',
    'dashboard.viewAll': '查看全部',
    'alerts.title': '警报中心',
    'alerts.subtitle': '监控和管理系统警报',
    'alerts.filter.all': '全部',
    'alerts.filter.critical': '危急',
    'alerts.filter.warning': '警告',
    'alerts.filter.info': '信息',
    'alerts.acknowledge': '确认',
    'alerts.acknowledged': '已确认',
    'alerts.details': '详情',
    'alerts.sampleTitle': '示例警报。',
    'alerts.sampleBody': '这些条目由 {company} 的原始数据测量得出——来源表、字段和实测值显示在每条警报下方。它们用于演示警报流程；没有实时连接。',
    'alerts.sampleBadge': '示例',
    'common.apply': '应用',
    'common.dismiss': '忽略',
    'common.seeDetails': '查看详情',
    'common.export': '导出',
    'common.loading': '加载中...',
    'common.error': '发生错误。请重试。',
    'common.noData': '暂无数据',
    'onboarding.welcome': '欢迎使用 SMAP',
    'onboarding.step1.title': '仪表板概览',
    'onboarding.step1.desc': '一目了然地监控您的关键绩效指标和系统健康状态。',
    'onboarding.step2.title': '认知数字孪生',
    'onboarding.step2.desc': '探索实时数字表示并运行假设分析仿真。',
    'onboarding.step3.title': '决策支持与可持续性',
    'onboarding.step3.desc': '获取AI驱动的优化建议和可持续性评估。',
    'onboarding.step4.title': '警报中心',
    'onboarding.step4.desc': '随时了解关键事件和系统通知。',
    'onboarding.next': '下一步',
    'onboarding.prev': '上一步',
    'onboarding.finish': '开始使用',
    'onboarding.skip': '跳过导览',
    'onboarding.dontShowAgain': '不再显示',
    'adminTour.welcome': '欢迎使用 SMAP 管理后台',
    'adminTour.step1.title': '用户与角色',
    'adminTour.step1.desc': '创建、编辑和删除账户，并分配经理、工程师或操作员角色。您只能查看和管理本用例的用户。',
    'adminTour.step2.title': '页面与卡片',
    'adminTour.step2.desc': '决定每个角色可以看到哪些页面和哪些卡片。更改会立即在该角色的视图中生效。',
    'adminTour.step3.title': '范围与存储',
    'adminTour.step3.desc': '这是演示配置，仅保存在本浏览器中。它仅涵盖您自己的用例；另一个用例由其自己的管理员账户配置。',
    // --- Digital Twin pages (T4.2 i18n) — taslak çeviri / draft ---
    'dt.actual': '实际',
    'dt.target': '目标',
    'dt.planned': '计划',
    'dt.inbound': '入库',
    'dt.outbound': '出库',
    'dt.suppliers': '供应商',
    'dt.production': '生产',
    'dt.customers': '客户',
    'dt.count': '数量',
    'dt.onTrack': '正常',
    'dt.onTime': '准时',
    'dt.atRisk': '有风险',
    'dt.delayed': '延迟',
    'common.source': '来源',
    'vcdt.title': '价值链数字孪生',
    'vcdt.subtitle': '覆盖整个供应网络的端到端可见性',
    'vcdt.supplyChainFlow': '供应链流程',
    'vcdt.leadTimeTrend': '交付周期趋势',
    'vcdt.orderStatus': '订单状态',
    'vcdt.networkNodes': '网络节点',
    'vcdt.totalOrders': '订单总数',
    'vcdt.help': '查看涵盖供应商、生产、仓储和配送的端到端价值链。每个节点显示其健康状态和 KPI。使用流程图和交付周期趋势来识别瓶颈。',
    'vcdt.helpLink': '价值链 DT 指南',
    'mfg.title': '制造数字孪生',
    'mfg.subtitle': '实时生产监控与设备状态',
    'mfg.exportReport': '制造数字孪生分析报告',
    'mfg.productionOutput': '生产产量',
    'mfg.oeeTitle': 'OEE — 可用率 × 性能 × 质量',
    'mfg.oeeKpiBy': 'KPI 由 IDE（KAM）和 JPB 定义',
    'mfg.oeeDesc': '在每个分项都连接到数据源之前不显示数值。三项中有两项可由当前数据计算；可用率随设备数据流到达。',
    'mfg.machineStatus': '设备状态',
    'mfg.machineStatusDesc': '按单元的状态摘要。ERP 导出不含设备标识或停机时间，因此该视图列出在数据流接入后将据以构建的四种 UnitMode。',
    'mfg.materialReadiness': '物料齐套',
    'mfg.materialReadinessDesc': '未结和已结工单的物料发放状态。',
    'mfg.matCompletelyIssued': '已全部发放',
    'mfg.matPartiallyIssued': '部分发放',
    'mfg.matNotReserved': '未预留',
    'mfg.pctOfTotal': '{total} 中的 {pct}%',
    'mfg.actualVsPlanned': '实际与计划工时对比',
    'mfg.actualVsPlannedDesc': '按工序阶段，实际记录工时与工艺标准的对比。',
    'mfg.cycleTime': '节拍时间分析',
    'mfg.actualSec': '实际（秒）',
    'mfg.targetSec': '目标（秒）',
    'mfg.legAvailability': '可用率',
    'mfg.legPerformance': '性能',
    'mfg.legQuality': '质量',
    'mfg.noteAvailability': '随设备数据流（Kafka）到达。ERP 导出中不存在。',
    'mfg.notePerformance': '现可由车间工时跟踪计算。',
    'mfg.modeProduction': '生产',
    'mfg.modeMaintenance': '维护',
    'mfg.modeManual': '手动',
    'mfg.modeChangeover': '换型',
    'mfg.noteModeProduction': '正常生产模式。',
    'mfg.noteModeMaintenance': '设备维护中。',
    'mfg.noteModeManual': '在手动控制下运行。',
    'mfg.noteModeChangeover': '正在更换夹具／部件。',
    'mfg.sourceAvailable': '来源可用',
    'mfg.awaitingStream': '等待数据流',
    'logi.title': '物流数字孪生',
    'logi.subtitle': '运输与配送监控',
    'logi.volumeTrend': '吞吐量趋势',
    'logi.routePerformance': '路线绩效',
    'logi.activeShipments': '在途货运',
    'logi.timeDays': '时间（天）',
    'logi.targetDays': '目标（天）',
    'logi.shipments': '货运',
    'logi.shipInTransit': '运输中',
    'logi.shipDelivered': '已送达',
    'logi.shipPending': '待处理',
    'logi.shipDelayed': '延迟',
    'logi.thShipmentId': '货运编号',
    'logi.thDestination': '目的地',
    'logi.thEta': '预计到达',
    'logi.thStatus': '状态',
    'logi.thProgress': '进度',
    'logi.help': '监控实时物流数据，包括交付准确性、路线绩效和在途货运。状态指示器显示每批货运的当前状态——运输中、延迟或已送达。',
    'logi.helpLink': '物流 DT 指南',
    'prod.title': '产品数字孪生',
    'prod.subtitle': '质量监控与产品可追溯性',
    'prod.qualityTrend': '按批次的质量趋势',
    'prod.defectDistribution': '缺陷分布',
    'prod.productVariants': '产品变体绩效',
    'prod.componentTraceability': '组件可追溯性',
    'prod.receiptInspection': '来料检验',
    'prod.yieldPct': '良率 %',
    'prod.defectsPct': '缺陷率 %',
    'prod.yieldRate': '良率',
    'prod.volume': '产量',
    'prod.searchComponent': '搜索组件...',
    'prod.thComponent': '组件',
    'prod.thLot': '批次',
    'prod.thCertificate': '证书',
    'prod.thReceived': '接收日期',
    'prod.thQty': '数量',
    'prod.thStatus': '状态',
    'prod.thPart': '零件',
    'prod.thArrived': '到货',
    'prod.thInspected': '已检验',
    'prod.thScrapped': '报废',
    'prod.thReturned': '退回',
    'prod.helpTrace': '跟踪产品组件在整个供应链中的流转。点击某个产品变体可查看批次质量、缺陷分布和可追溯性数据。红色行表示检验未通过——点击查看详情。',
    'prod.helpReceipt': '按零件进行的来料验收控制：到货多少、检验多少、报废或退回多少。KAM 不保留批号，因此来料按数量而非批次跟踪。',
    'prod.helpLink': '产品 DT 指南',
  },
  tr: {
    'nav.dashboard': 'Kontrol Paneli',
    'nav.digitalTwin': 'Bilişsel Dijital İkizler',
    'nav.valueChain': 'Değer Zinciri DT',
    'nav.valueChainSim': 'Değer Zinciri Simülasyonu',
    'nav.manufacturing': 'Üretim Hattı DT',
    'nav.manufacturingSim': 'Üretim Simülasyonu',
    'nav.logistics': 'Lojistik DT',
    'nav.product': 'Ürün DT',
    'nav.sustainability': 'Sürdürülebilirlik Değerlendirmesi',
    'nav.decisionSupport': 'Karar Destek',
    'nav.moDss': 'Çok Amaçlı Optimizasyon',
    'nav.knowledgeGraph': 'Karar Bilgi Grafı',
    'nav.alertCenter': 'Uyarı Merkezi',
    'nav.glossary': 'Terimler Sözlüğü',
    'nav.helpTraining': 'Yardım ve Eğitim',
    'header.search': 'Ara...',
    'header.lastHours': 'Son 24 Saat',
    'header.last7Days': 'Son 7 Gün',
    'header.last30Days': 'Son 30 Gün',
    'header.last90Days': 'Son 90 Gün',
    'header.refresh': 'Verileri yenile',
    'header.notifications': 'Bildirimler',
    'header.language': 'Dil',
    'status.online': 'Sistem Çevrimiçi',
    'status.warning': 'Sistem Uyarısı',
    'status.critical': 'Sistem Kritik',
    'dashboard.title': 'Operasyon Paneli',
    'dashboard.subtitle': 'Değer zinciri performansının gerçek zamanlı görünümü',
    'dashboard.kpi.oee': 'Toplam Ekipman Verimliliği',
    'dashboard.kpi.throughput': 'Günlük Üretim',
    'dashboard.kpi.defectRate': 'Hata Oranı',
    'dashboard.kpi.energyEfficiency': 'Enerji Verimliliği',
    'dashboard.kpi.sustainability': 'Sürdürülebilirlik Puanı',
    'dashboard.kpi.supplyChainRisk': 'Tedarik Zinciri Risk Endeksi',
    'dashboard.alerts': 'Son Uyarılar',
    'dashboard.viewAll': 'Tümünü Gör',
    'alerts.title': 'Uyarı Merkezi',
    'alerts.subtitle': 'Sistem uyarılarını izle ve yönet',
    'alerts.filter.all': 'Tümü',
    'alerts.filter.critical': 'Kritik',
    'alerts.filter.warning': 'Uyarı',
    'alerts.filter.info': 'Bilgi',
    'alerts.acknowledge': 'Onayla',
    'alerts.acknowledged': 'Onaylandı',
    'alerts.details': 'Detaylar',
    'alerts.sampleTitle': 'Örnek alarmlar.',
    'alerts.sampleBody': 'Bu kayıtlar {company} ham verisinden ölçülmüştür — kaynak tablo, kolon ve ölçülen değer her alarmın altında yazılıdır. Alarm akışını göstermek içindir; canlı bağlantı yoktur.',
    'alerts.sampleBadge': 'Örnek',
    'common.apply': 'Uygula',
    'common.dismiss': 'Yoksay',
    'common.seeDetails': 'Detayları Gör',
    'common.export': 'Dışa Aktar',
    'common.loading': 'Yükleniyor...',
    'common.error': 'Bir hata oluştu. Lütfen tekrar deneyin.',
    'common.noData': 'Veri bulunamadı',
    'onboarding.welcome': "SMAP'e Hoş Geldiniz",
    'onboarding.step1.title': 'Panele Genel Bakış',
    'onboarding.step1.desc': 'Temel performans göstergelerinizi ve sistem durumunu bir bakışta izleyin.',
    'onboarding.step2.title': 'Bilişsel Dijital İkizler',
    'onboarding.step2.desc': 'Gerçek zamanlı dijital temsilleri keşfedin ve senaryo (what-if) simülasyonları çalıştırın.',
    'onboarding.step3.title': 'Karar Destek ve Sürdürülebilirlik',
    'onboarding.step3.desc': 'Yapay zekâ destekli optimizasyon önerileri ve sürdürülebilirlik değerlendirmeleri alın.',
    'onboarding.step4.title': 'Uyarı Merkezi',
    'onboarding.step4.desc': 'Kritik olaylar ve sistem bildirimleri hakkında bilgi sahibi olun.',
    'onboarding.next': 'İleri',
    'onboarding.prev': 'Geri',
    'onboarding.finish': 'Başla',
    'onboarding.skip': 'Turu Atla',
    'onboarding.dontShowAgain': 'Bir daha gösterme',
    'adminTour.welcome': "SMAP Admin'e Hoş Geldiniz",
    'adminTour.step1.title': 'Kullanıcılar ve Roller',
    'adminTour.step1.desc': 'Hesap oluşturun, düzenleyin ve silin; yönetici, mühendis veya operatör rolünü atayın. Yalnızca kendi kullanım senaryonuzun kullanıcılarını görür ve yönetirsiniz.',
    'adminTour.step2.title': 'Sayfalar ve Kartlar',
    'adminTour.step2.desc': 'Hangi sayfayı ve hangi kartı hangi rolün göreceğine buradan karar verirsiniz. Değişiklik, o rolün görünümüne anında yansır.',
    'adminTour.step3.title': 'Kapsam ve saklama',
    'adminTour.step3.desc': 'Bu bir demo yapılandırmasıdır ve yalnızca bu tarayıcıda saklanır. Kendi kullanım senaryonuzu kapsar; diğer senaryo kendi yönetici hesabından yapılandırılır.',
    // --- Dijital İkiz sayfaları (T4.2 i18n) — tr referans metin ---
    'dt.actual': 'Gerçekleşen',
    'dt.target': 'Hedef',
    'dt.planned': 'Planlanan',
    'dt.inbound': 'Gelen',
    'dt.outbound': 'Giden',
    'dt.suppliers': 'Tedarikçiler',
    'dt.production': 'Üretim',
    'dt.customers': 'Müşteriler',
    'dt.count': 'Adet',
    'dt.onTrack': 'Yolunda',
    'dt.onTime': 'Zamanında',
    'dt.atRisk': 'Riskli',
    'dt.delayed': 'Gecikti',
    'common.source': 'Kaynak',
    'vcdt.title': 'Değer Zinciri Dijital İkizi',
    'vcdt.subtitle': 'Tedarik ağında uçtan uca görünürlük',
    'vcdt.supplyChainFlow': 'Tedarik Zinciri Akışı',
    'vcdt.leadTimeTrend': 'Tedarik Süresi Eğilimi',
    'vcdt.orderStatus': 'Sipariş Durumu',
    'vcdt.networkNodes': 'Ağ Düğümleri',
    'vcdt.totalOrders': 'Toplam Sipariş',
    'vcdt.help': "Tedarikçiler, üretim, depolama ve dağıtım dahil uçtan uca değer zincirini görüntüleyin. Her düğüm kendi sağlık durumunu ve KPI'larını gösterir. Darboğazları belirlemek için akış şemasını ve tedarik süresi eğilimini kullanın.",
    'vcdt.helpLink': 'Değer Zinciri DT kılavuzu',
    'mfg.title': 'Üretim Dijital İkizi',
    'mfg.subtitle': 'Gerçek zamanlı üretim izleme ve ekipman durumu',
    'mfg.exportReport': 'Üretim Dijital İkizi Analiz Raporu',
    'mfg.productionOutput': 'Üretim Çıktısı',
    'mfg.oeeTitle': 'OEE — Kullanılabilirlik × Performans × Kalite',
    'mfg.oeeKpiBy': 'KPI, IDE (KAM) ve JPB tarafından tanımlandı',
    'mfg.oeeDesc': 'Her bileşenin bağlı bir kaynağı olana kadar değer gösterilmez. Üçünden ikisi mevcut verilerden hesaplanabilir; Kullanılabilirlik ekipman akışıyla gelir.',
    'mfg.machineStatus': 'Makine Durumu',
    'mfg.machineStatusDesc': "Birim bazında durum özeti. ERP ihracı makine kimliği veya duruş süresi taşımaz; bu nedenle bu görünüm, akış bağlandığında üzerine kurulacağı dört UnitMode'u listeler.",
    'mfg.materialReadiness': 'Malzeme Hazırlığı',
    'mfg.materialReadinessDesc': 'Açık ve kapalı iş emirlerinde malzeme çıkış durumu.',
    'mfg.matCompletelyIssued': 'Tamamen Verildi',
    'mfg.matPartiallyIssued': 'Kısmen Verildi',
    'mfg.matNotReserved': 'Rezerve Edilmedi',
    'mfg.pctOfTotal': '{total} içinde %{pct}',
    'mfg.actualVsPlanned': 'Gerçekleşen vs Planlanan Saat',
    'mfg.actualVsPlannedDesc': 'Operasyon fazına göre, rota standardına karşı kaydedilen saatler.',
    'mfg.cycleTime': 'Çevrim Süresi Analizi',
    'mfg.actualSec': 'Gerçekleşen (sn)',
    'mfg.targetSec': 'Hedef (sn)',
    'mfg.legAvailability': 'Kullanılabilirlik',
    'mfg.legPerformance': 'Performans',
    'mfg.legQuality': 'Kalite',
    'mfg.noteAvailability': 'Ekipman akışıyla (Kafka) gelir. ERP ihracında bulunmaz.',
    'mfg.notePerformance': 'Atölye zaman takibinden bugün hesaplanabilir.',
    'mfg.modeProduction': 'Üretim',
    'mfg.modeMaintenance': 'Bakım',
    'mfg.modeManual': 'Manuel',
    'mfg.modeChangeover': 'Ürün Değişimi',
    'mfg.noteModeProduction': 'Normal üretim modu.',
    'mfg.noteModeMaintenance': 'Ekipman bakımda.',
    'mfg.noteModeManual': 'Manuel kontrol altında çalışma.',
    'mfg.noteModeChangeover': 'Aparatlar / bileşenler değiştiriliyor.',
    'mfg.sourceAvailable': 'kaynak mevcut',
    'mfg.awaitingStream': 'akış bekleniyor',
    'logi.title': 'Lojistik Dijital İkizi',
    'logi.subtitle': 'Taşıma ve dağıtım izleme',
    'logi.volumeTrend': 'Hacim Eğilimi',
    'logi.routePerformance': 'Rota Performansı',
    'logi.activeShipments': 'Aktif Sevkiyatlar',
    'logi.timeDays': 'Süre (gün)',
    'logi.targetDays': 'Hedef (gün)',
    'logi.shipments': 'sevkiyat',
    'logi.shipInTransit': 'Yolda',
    'logi.shipDelivered': 'Teslim Edildi',
    'logi.shipPending': 'Beklemede',
    'logi.shipDelayed': 'Gecikti',
    'logi.thShipmentId': 'Sevkiyat No',
    'logi.thDestination': 'Varış Yeri',
    'logi.thEta': 'ETA',
    'logi.thStatus': 'Durum',
    'logi.thProgress': 'İlerleme',
    'logi.help': 'Teslimat doğruluğu, rota performansı ve aktif sevkiyatlar dahil gerçek zamanlı lojistik verilerini izleyin. Durum göstergeleri her sevkiyatın güncel durumunu gösterir — Yolda, Gecikti veya Teslim Edildi.',
    'logi.helpLink': 'Lojistik DT kılavuzu',
    'prod.title': 'Ürün Dijital İkizi',
    'prod.subtitle': 'Kalite izleme ve ürün izlenebilirliği',
    'prod.qualityTrend': 'Partiye Göre Kalite Eğilimi',
    'prod.defectDistribution': 'Hata Dağılımı',
    'prod.productVariants': 'Ürün Varyantı Performansı',
    'prod.componentTraceability': 'Bileşen İzlenebilirliği',
    'prod.receiptInspection': 'Mal Kabul Muayenesi',
    'prod.yieldPct': 'Verim %',
    'prod.defectsPct': 'Hata %',
    'prod.yieldRate': 'Verim Oranı',
    'prod.volume': 'Hacim',
    'prod.searchComponent': 'Bileşen ara...',
    'prod.thComponent': 'Bileşen',
    'prod.thLot': 'Parti',
    'prod.thCertificate': 'Sertifika',
    'prod.thReceived': 'Giriş Tarihi',
    'prod.thQty': 'Miktar',
    'prod.thStatus': 'Durum',
    'prod.thPart': 'Parça',
    'prod.thArrived': 'Gelen',
    'prod.thInspected': 'Muayene Edilen',
    'prod.thScrapped': 'Hurdaya Ayrılan',
    'prod.thReturned': 'İade Edilen',
    'prod.helpTrace': 'Ürün bileşenlerini tedarik zinciri boyunca izleyin. Parti kalitesini, hata dağılımını ve izlenebilirlik verilerini incelemek için bir ürün varyantına tıklayın. Kırmızı satırlar muayene hatalarını gösterir — ayrıntılar için tıklayın.',
    'prod.helpReceipt': 'Parça bazında mal kabul kontrolü: ne kadarı geldi, ne kadarı muayene edildi, ne kadarı hurdaya ayrıldı veya iade edildi. KAM parti numarası tutmadığından gelen malzeme parti yerine miktara göre izlenir.',
    'prod.helpLink': 'Ürün DT kılavuzu',
  },
  da: {
    // --- Danca (da) — 7. dil, TAM sözlük. Tümü model üretimi taslaktır;
    //     native Danca gözden geçirme önerilir (T4.2 i18n, 2026-09-09). ---
    'nav.dashboard': 'Dashboard',
    'nav.digitalTwin': 'Drift',
    'nav.valueChain': 'Værdikæde DT',
    'nav.valueChainSim': 'Værdikædesimulering',
    'nav.manufacturing': 'Produktion DT',
    'nav.manufacturingSim': 'Produktionssimulering',
    'nav.logistics': 'Logistik DT',
    'nav.product': 'Produkt DT',
    'nav.sustainability': 'Bæredygtighedsvurdering',
    'nav.decisionSupport': 'Beslutningsstøtte',
    'nav.moDss': 'Multi-objektiv optimering',
    'nav.knowledgeGraph': 'Beslutningsvidensgraf',
    'nav.alertCenter': 'Alarmcenter',
    'nav.glossary': 'Ordliste',
    'nav.helpTraining': 'Hjælp og oplæring',
    'header.search': 'Søg...',
    'header.lastHours': 'Seneste 24 timer',
    'header.last7Days': 'Seneste 7 dage',
    'header.last30Days': 'Seneste 30 dage',
    'header.last90Days': 'Seneste 90 dage',
    'header.refresh': 'Opdater data',
    'header.notifications': 'Notifikationer',
    'header.language': 'Sprog',
    'status.online': 'System online',
    'status.warning': 'Systemadvarsel',
    'status.critical': 'System kritisk',
    'dashboard.title': 'Driftsdashboard',
    'dashboard.subtitle': 'Realtidsoverblik over værdikædens ydeevne',
    'dashboard.kpi.oee': 'Samlet udstyrseffektivitet',
    'dashboard.kpi.throughput': 'Daglig gennemstrømning',
    'dashboard.kpi.defectRate': 'Fejlrate',
    'dashboard.kpi.energyEfficiency': 'Energieffektivitet',
    'dashboard.kpi.sustainability': 'Bæredygtighedsscore',
    'dashboard.kpi.supplyChainRisk': 'Forsyningskæderisikoindeks',
    'dashboard.alerts': 'Seneste alarmer',
    'dashboard.viewAll': 'Vis alle',
    'alerts.title': 'Alarmcenter',
    'alerts.subtitle': 'Overvåg og administrer systemalarmer',
    'alerts.filter.all': 'Alle',
    'alerts.filter.critical': 'Kritiske',
    'alerts.filter.warning': 'Advarsel',
    'alerts.filter.info': 'Info',
    'alerts.acknowledge': 'Bekræft',
    'alerts.acknowledged': 'Bekræftet',
    'alerts.details': 'Detaljer',
    'alerts.sampleTitle': 'Eksempelalarmer.',
    'alerts.sampleBody': 'Disse poster er målt ud fra {company}s rådata — kildetabel, kolonne og målt værdi står under hver alarm. De illustrerer alarmforløbet; der er ingen live-forbindelse.',
    'alerts.sampleBadge': 'Eksempel',
    'common.apply': 'Anvend',
    'common.dismiss': 'Afvis',
    'common.seeDetails': 'Se detaljer',
    'common.export': 'Eksportér',
    'common.loading': 'Indlæser...',
    'common.error': 'Der opstod en fejl. Prøv igen.',
    'common.noData': 'Ingen data tilgængelige',
    'onboarding.welcome': 'Velkommen til SMAP',
    'onboarding.step1.title': 'Dashboard-overblik',
    'onboarding.step1.desc': 'Overvåg dine vigtigste nøgletal og systemets tilstand på ét blik.',
    'onboarding.step2.title': 'Kognitive digitale tvillinger',
    'onboarding.step2.desc': 'Udforsk digitale repræsentationer i realtid og kør hvad-nu-hvis-simuleringer.',
    'onboarding.step3.title': 'Beslutningsstøtte og bæredygtighed',
    'onboarding.step3.desc': 'Få AI-drevne optimeringsanbefalinger og bæredygtighedsvurderinger.',
    'onboarding.step4.title': 'Alarmcenter',
    'onboarding.step4.desc': 'Hold dig orienteret om kritiske hændelser og systemnotifikationer.',
    'onboarding.next': 'Næste',
    'onboarding.prev': 'Forrige',
    'onboarding.finish': 'Kom i gang',
    'onboarding.skip': 'Spring rundvisning over',
    'onboarding.dontShowAgain': 'Vis ikke dette igen',
    'adminTour.welcome': 'Velkommen til SMAP Admin',
    'adminTour.step1.title': 'Brugere og roller',
    'adminTour.step1.desc': 'Opret, rediger og fjern konti, og tildel rollen leder, ingeniør eller operatør. Du ser og administrerer kun brugere i din egen anvendelse.',
    'adminTour.step2.title': 'Sider og kort',
    'adminTour.step2.desc': 'Bestem hvilke sider og hvilke kort hver rolle kan se. En ændring træder i kraft med det samme i den pågældende rolles visning.',
    'adminTour.step3.title': 'Omfang og lagring',
    'adminTour.step3.desc': 'Dette er en demokonfiguration og gemmes kun i denne browser. Den dækker din egen anvendelse; den anden anvendelse konfigureres fra sin egen administratorkonto.',
    // --- Digital Twin pages (T4.2 i18n) ---
    'dt.actual': 'Faktisk',
    'dt.target': 'Mål',
    'dt.planned': 'Planlagt',
    'dt.inbound': 'Indgående',
    'dt.outbound': 'Udgående',
    'dt.suppliers': 'Leverandører',
    'dt.production': 'Produktion',
    'dt.customers': 'Kunder',
    'dt.count': 'Antal',
    'dt.onTrack': 'På sporet',
    'dt.onTime': 'Til tiden',
    'dt.atRisk': 'I risiko',
    'dt.delayed': 'Forsinket',
    'common.source': 'Kilde',
    'vcdt.title': 'Digital tvilling for værdikæde',
    'vcdt.subtitle': 'Ende-til-ende-synlighed på tværs af forsyningsnetværket',
    'vcdt.supplyChainFlow': 'Forsyningskædeflow',
    'vcdt.leadTimeTrend': 'Gennemløbstidstendens',
    'vcdt.orderStatus': 'Ordrestatus',
    'vcdt.networkNodes': 'Netværksknuder',
    'vcdt.totalOrders': 'Ordrer i alt',
    'vcdt.help': "Se hele værdikæden fra ende til ende, inklusive leverandører, produktion, lager og distribution. Hver knude viser sin tilstand og sine KPI'er. Brug flowdiagrammet og gennemløbstidstendensen til at finde flaskehalse.",
    'vcdt.helpLink': 'Vejledning til værdikæde-DT',
    'mfg.title': 'Digital tvilling for produktion',
    'mfg.subtitle': 'Produktionsovervågning i realtid og udstyrsstatus',
    'mfg.exportReport': 'Analyserapport for digital tvilling for produktion',
    'mfg.productionOutput': 'Produktionsoutput',
    'mfg.oeeTitle': 'OEE — Tilgængelighed × Ydelse × Kvalitet',
    'mfg.oeeKpiBy': 'KPI defineret af IDE (KAM) og JPB',
    'mfg.oeeDesc': 'Der vises ingen værdi, før hver delkomponent har en tilsluttet kilde. To af de tre kan beregnes ud fra de aktuelle data; tilgængelighed kommer med udstyrsstrømmen.',
    'mfg.machineStatus': 'Maskinstatus',
    'mfg.machineStatusDesc': 'Tilstandsoversigt pr. enhed. ERP-udtrækket indeholder ingen maskinidentitet eller nedetid, så denne visning viser de fire UnitModes, den bygges ud fra, når strømmen er tilsluttet.',
    'mfg.materialReadiness': 'Materialeparathed',
    'mfg.materialReadinessDesc': 'Materialeudleveringsstatus på tværs af åbne og lukkede produktionsordrer.',
    'mfg.matCompletelyIssued': 'Fuldt udleveret',
    'mfg.matPartiallyIssued': 'Delvist udleveret',
    'mfg.matNotReserved': 'Ikke reserveret',
    'mfg.pctOfTotal': '{pct}% af {total}',
    'mfg.actualVsPlanned': 'Faktiske vs. planlagte timer',
    'mfg.actualVsPlannedDesc': 'Registrerede timer i forhold til rutestandarden, pr. operationsfase.',
    'mfg.cycleTime': 'Cyklustidsanalyse',
    'mfg.actualSec': 'Faktisk (sek.)',
    'mfg.targetSec': 'Mål (sek.)',
    'mfg.legAvailability': 'Tilgængelighed',
    'mfg.legPerformance': 'Ydelse',
    'mfg.legQuality': 'Kvalitet',
    'mfg.noteAvailability': 'Kommer med udstyrsstrømmen (Kafka). Findes ikke i ERP-udtrækket.',
    'mfg.notePerformance': 'Kan beregnes i dag ud fra tidsregistreringen på værkstedet.',
    'mfg.modeProduction': 'Produktion',
    'mfg.modeMaintenance': 'Vedligeholdelse',
    'mfg.modeManual': 'Manuel',
    'mfg.modeChangeover': 'Omstilling',
    'mfg.noteModeProduction': 'Normal produktionstilstand.',
    'mfg.noteModeMaintenance': 'Udstyr under vedligeholdelse.',
    'mfg.noteModeManual': 'Kørsel under manuel styring.',
    'mfg.noteModeChangeover': 'Værktøj / komponenter udskiftes.',
    'mfg.sourceAvailable': 'kilde tilgængelig',
    'mfg.awaitingStream': 'afventer strøm',
    'logi.title': 'Digital tvilling for logistik',
    'logi.subtitle': 'Overvågning af transport og distribution',
    'logi.volumeTrend': 'Volumentendens',
    'logi.routePerformance': 'Ruteydelse',
    'logi.activeShipments': 'Aktive forsendelser',
    'logi.timeDays': 'Tid (dage)',
    'logi.targetDays': 'Mål (dage)',
    'logi.shipments': 'forsendelser',
    'logi.shipInTransit': 'Undervejs',
    'logi.shipDelivered': 'Leveret',
    'logi.shipPending': 'Afventer',
    'logi.shipDelayed': 'Forsinket',
    'logi.thShipmentId': 'Forsendelses-ID',
    'logi.thDestination': 'Destination',
    'logi.thEta': 'ETA',
    'logi.thStatus': 'Status',
    'logi.thProgress': 'Fremdrift',
    'logi.help': 'Overvåg logistikdata i realtid, inklusive leveringspræcision, ruteydelse og aktive forsendelser. Statusindikatorer viser hver forsendelses aktuelle tilstand — Undervejs, Forsinket eller Leveret.',
    'logi.helpLink': 'Vejledning til logistik-DT',
    'prod.title': 'Digital tvilling for produkt',
    'prod.subtitle': 'Kvalitetsovervågning og produktsporbarhed',
    'prod.qualityTrend': 'Kvalitetstendens pr. batch',
    'prod.defectDistribution': 'Fejlfordeling',
    'prod.productVariants': 'Ydelse for produktvarianter',
    'prod.componentTraceability': 'Komponentsporbarhed',
    'prod.receiptInspection': 'Modtagekontrol',
    'prod.yieldPct': 'Udbytte %',
    'prod.defectsPct': 'Fejl %',
    'prod.yieldRate': 'Udbytterate',
    'prod.volume': 'Volumen',
    'prod.searchComponent': 'Søg komponent...',
    'prod.thComponent': 'Komponent',
    'prod.thLot': 'Parti',
    'prod.thCertificate': 'Certifikat',
    'prod.thReceived': 'Modtaget',
    'prod.thQty': 'Antal',
    'prod.thStatus': 'Status',
    'prod.thPart': 'Del',
    'prod.thArrived': 'Ankommet',
    'prod.thInspected': 'Inspiceret',
    'prod.thScrapped': 'Kasseret',
    'prod.thReturned': 'Returneret',
    'prod.helpTrace': 'Spor produktkomponenter gennem hele forsyningskæden. Klik på en produktvariant for at inspicere batchkvalitet, fejlfordeling og sporbarhedsdata. Røde rækker angiver inspektionsfejl — klik for at se detaljer.',
    'prod.helpReceipt': 'Varemodtagekontrol pr. del: hvor meget der ankom, hvor meget der blev inspiceret, og hvor meget der blev kasseret eller returneret. KAM fører ikke partinumre, så indgående materiale spores efter mængde frem for efter batch.',
    'prod.helpLink': 'Vejledning til produkt-DT',
  },
};

/*
 * VERİ-KAYNAKLI ETİKET SÖZLÜĞÜNÜ birleştir (T4.2 (i) takip).
 * KpiCard / ValueChainDT gibi bileşenlerde veri kaynağından (mockData.ts /
 * pageLayouts.ts) gelen ve önceden t()'yi baypas eden başlık/etiket/birim/
 * kategori/düğüm metinleri artık 'dkpi.*', 'dcluster.*', 'dunit.*', 'dnode.*',
 * 'dtype.*', 'dmetric.*', 'dcard.*' anahtarlarıyla buraya bağlanır ve normal
 * t() ile aktif dile çözülür. Yükleme anında bir kez çalışır. Bkz.
 * src/i18n/dataLabels.ts (taslak çeviri notu orada).
 */
for (const lang of Object.keys(translations) as Language[]) {
  Object.assign(translations[lang], DATA_LABEL_TRANSLATIONS[lang]);
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('smap-language');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('smap-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
